services:
  mqtt-simulator:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    image: mqtt-simulator-image
    container_name: ctn-simulator-server
    hostname: simulator-server
    networks:
      - hanshen_network
    # ports:
    #   - 80:8080
    # environment:
    #   - PGUSER=${PGUSER:-totoro}
    #   - PGPASSWORD=${PGPASSWORD:?database password not set}
    #   - PGHOST=${PGHOST:-db}
    #   - PGPORT=${PGPORT:-26257}
    #   - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  # roach:
  #   image: cockroachdb/cockroach:latest-v20.1
  #   container_name: roach
  #   hostname: db
  #   networks:
  #     - mynet
  #   ports:
  #     - 26257:26257
  #     - 8080:8080
  #   volumes:
  #     - roach:/cockroach/cockroach-data
  #   command: start-single-node --insecure

volumes:
  hanshen_vol:

networks:
  hanshen_network:
    driver: bridge